web:
  build: .
  links:
    - db
  volumes:
    - ./app:/var/www/app
  ports:
    - "8080:80"
    - "3001:3001"
    - "3000:3000"
db:
  image: tutum/mysql
  environment:
    MYSQL_USER: silver
    MYSQL_PASS: password
  volumes:
    - ./Mysql:/var/lib/mysql
    - ./MysqlHome:/root
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 81:80
  links:
      - db
  environment:
    PMA_HOST: db